import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'dart:math';

// sample jokes data
final List<String> jokesItems = [
  "A man walked into an appliance store and asked the price of a 25\" remote controlled color television set. \"One dollar,\" the clerk replied. \"You've got to be kidding. \" \"Look, Mac,\" the clerk said, \"do you want it or not? \" Of course, the customer gave him a dollar. On the way out with his incredible bargain, the cuctomer saw a big frost-free refrigerator with automatic ice maker. \"How much for that? \" he asked the clerk. \"Fifty cents,\" came the reply. The customer forked over the half dollar, saying, \"What the heck is going on here? \" \"Nothing is going on here,\" the clerk snapped. \"But my boss is at my house with my wife. And what he's doing to her, I'm doing to his business. \"",
  "A guy finally gets a date with an easy blonde. To prepare for the date he sunbathes in the nude on his roof, falls asleep and burns his manhood. He doesn't want to cancel so he slathers it with lotion and wraps it in gauze. The blonde shows up at his house, and he treats her to a home-cooked dinner. Afterwards they go to the living room to watch a movie. His manhood starts to bother him again so he excuses himself, goes into the kitchen, pours a glass of milk and immerses himself for immediate relief. The blonde, however, wanted to know what he was doing and walks in on him with his Johnson in the milk and exclaims, \"So that's how you guys load those things! \"",
  "A 90 year old man shows up for a physical. He tells the doctor he is about to marry a 20 year old girl. \"Really? \" said the doctor. \"You're healthy enough, I suppose, but take my advice. If you want a happy marriage, you should take in a boarder. Do you know what I mean? \"The old man says, \"OK, doc. I'll think about it. \" Six months later, the doctor sees the old man on the street. He asks him how his new marriage is working out. \"Great doc! In fact, my wife is pregnant. \"The doctor nods knowingly and says, \"So you took my advice and took in a boarder? \"The old man winked and said, \"Yep. And she's pregnant too! \"",
  "A salesman was testifying in his divorce proceedings against his wife. \"Please describe,\" said his attorney, \"the incident that first caused you to entertain suspicions as to your wife's fidelity. \"Well, I'm pretty much on the road all week,\" the man testified. \"So naturally when I am home, I'm attentive to the wife. \" \"One Sunday morning,\" he continued,\"we were in the midst of some pretty heavy love-making when the old lady in the apartment next door pounded on the wall and yelled, 'Can't you at least stop all that racket on the weekends?'\"",
  "One day in school, the teacher decides to play 20 questions.\nSo the teacher says, \"okay kids, I am thinking of something round, and red.\"\nLittle Suzy pipes up, \"I know, it's a tomato.\"\n\"No, but you're thinking. It's an apple,\" replies the teacher.\nSo Little Johnny stands up, places his hand in his pocket and says, \"I am holding onto something that is round, hard, and has a head on it.\"\n\"Go to the principals office,\" says the teacher.\n\"No, it's not what you're thinking,\" says Johnny. \"It's a coin.\"",
  "Little Johnny's Dad got a call from Little Johnny's Spanish teacher. \"Your son's behavior in my class is unacceptable!\" She said.\nWhen Little Johnny got home, his Dad said \"I got a call from your Spanish teacher today. Would you like to tell me what that is all about? She says your behavior is unacceptable. I'm going to have to take away your video games for a week.\"\n\"Damn Mexicans!\" Johnny replied, \"you rebel a little & then they take away everything important to you!\"",
  "A few months after his parents were divorced, little Johnny passed by his mom's bedroom and saw her rubbing her body and moaning, \"I need a man, I need a man! \"Over the next couple of months, he saw her doing this several times.One day, he came home from school and heard her moaning. When he peeked into her bedroom, he saw a man on top of her. Little Johnny ran into his room, took off his clothes, threw himself on his bed, started stroking himself, and moaning, \"Ohh, I need a bike! I need a bike!\"",
  "A man is out shopping and discovers a new brand of Olympic condoms. Clearly impressed, he buys a pack. Upon getting home he announces to his wife the purchase he just made. ?Olympic condoms??, she blurts, ?What makes them so special?? ?There are three colours?, he replies, ?Gold, Silver and Bronze.? ?What colour are you going to wear tonight??, she asks cheekily. ?Gold of course?, says the man proudly. The wife responds ?Why don?t you wear Silver? It would be nice if you came second for a change!?",
  "A little boy about nine or ten, was siting on Santa's lap. \nSanta pointed his finger in the boys face, and said, \" George I know what you want for Christmas! A T-O-Y. \n\"Nope!\" replied George. \nThen again, pointing his finger in the boys face, \"You want C-A-N-D-Y.\" \nNope!\" replied George. \n\"Then just what the hell do you want,\" ask Santa. \nGeorge looked Santa in the face, pointing his finger, \"I want some P-U-S-S-Y! And don't tell me that you don't have any. Because I can smell it on your finger!!\"",
  "Man enters a drugstore and asks the pharmacist for a pack of condoms. The Pharmacist asks, ?What size?? to which the man replies, ?I?m not exactly sure.? The pharmacist grabs something from under the counter and hands it to the man, ?Well, take this board with holes, go to the bathroom and the hole your erect penis fits into is the correct size of condom for you.? 20 minutes later the man comes back and tells the pharmacist, ?I?ve changed my mind, I don?t need the condoms. How much is this board??",
  "The farmer was disturbed when he found out his son, Little Johnny, was masturbating several times a day out in the barn.\n\"Boy, you gotta quit that! Go out and git yo'self a wife.\"\nSo Little Johnny went out and found himself a pretty young girl, to whom he got married. But a week or so after the wedding, the farmer found Little Johnny choking the chicken again.\n\"You crazy boy!!\" he yelled, \"That Elli-Mae's a fine young gal!!\"\n\"I know Paw,\" Little Johnny replied, \"but her arm gits tired sometimes!\"",
  "One day Little Johnny came up to his father and asked, \"Dad, where did I come from?\"\nDad squirmed a bit, but thought it was time his son knew the facts of life. So, Dad told his son how the expression of love resulted in the beginning of life, how life developed and finally how a child was born. As Dad told the story, his son's eyes got wider and wider.\nWhen Dad was finished, Little Johnny said, \"Wow, that's really neat. That sure beats what Billy told me. He said that he came from Philadelphia.\"",
  "This old man visits his doctor and after a thorough examination, the doctor tells him, \"I have good news and bad news, what would you like to hear first?\"Patient: Well, give me the bad news first.Doctor: You have cancer, I estimate that you have about two years left.Patient: OH NO! That's awful! In two years, my life will be over! What kind of good news could you probably tell me, after this???Doctor: You also have Alzheimer's. In about three months you are going to forget everything I told you.",
  "A study in Scotland showed that the kind of \"male face\" a woman finds attractive can differ depending on where a woman is in her menstrual cycle. For instance, if she is post-menstrual she may be attracted to plain facial features. When pre-menstrual she can be attracted to more feminine features in a man. If she is ovulating she is attracted to men with rugged, masculine features, and if she is menstruating she is more prone to be attracted to a man with a pair of scissors shoved in his temple.",
  "Three nuns were talking. The first nun said, \"I was cleaning in Father's room the other day and do you know what I found? A bunch of pornographic magazines.\" \"What did you do?\" the other nuns asked. \"Well, of course I threw them in the trash.\" The second nun said, \"Well, I can top that. I was in Father's room putting away the laundry and I found a bunch of condoms!\" \"Oh my!\" gasped the other nuns. \"What did you do?\" they asked. \"I poked holes in all of them!\" she replied. The third nun fainted.",
  "A man is at the dentist's for a check-up. As the dentist leans over, he asks, \"Well... So you had oral sex this morning?\" \"How did you know?\" asks the man, embarrassed but also amazed at his dentist's perception. \"Was it the smell on my breath?\" \"No\" says the dentist. \"Well, did you see a pubic hair caught in my teeth?\" asks the man. \"No\" says the dentist. \"Well, what then? How did you know?\" asks the man, losing patience. The dentist says \"There's a little bit of shit on the end of your nose.\"",
  "A husband pinches his wifes arse and says: \"Do you know if you firm this up you could get rid of your girdle?\"\n\nThe wife annoyed, decided to bite her tongue and say nothing.\n\nLater that night in bed, the husband squeezed her tits and said: \"Do you know, if you firmed these up you could get rid of your bra?\"\n\nAbsolutely fuming, the wife reached over and grabbed his dick and said: \"Well do you know, if you firmed this up, we could get rid of the gardener, the milk man and your fucking brother?\"",
  "Burford is checking out of a hotel when suddenly he has to take a shit real bad. The toilet in his room isn't working, so he bolts down to use the lobby Men's Room, but all of the stalls are occupied, so he runs back up to his room, and in desperation, he drops his pants, uproots a plant, and takes a shit in the pot. Then he puts the plant back in the pot and leaves. Two weeks later, he gets a postcard from the hotel that says,\n\"Dear Mr. Burford... All is forgiven. Just tell us...where it is?\"",
  "Burford is checking out of a hotel when suddenly he has to take a shit real bad. The toilet in his room isn't working, so he bolts down to use the lobby Men's Room, but all of the stalls are occupied, so he runs back up to his room, and in desperation, he drops his pants, uproots a plant, and takes a shit in the pot. Then he puts the plant back in the pot and leaves. Two weeks later, he gets a postcard from the hotel that says,\n\"Dear Mr. Burford... All is forgiven. Just tell us...where it is?\"",
  "After working together for a while, Frank and Jane's office romance blossomed and they really developed the hots for each other. One day,they seize the opportunity to sneak into a supply closet to consummate their lust. \nFrank finds Jane very tight and difficult to enter, but finally succeeds. \nWhen they are finished, Frank says to her, \"If I had known you were a virgin, I would have taken more time!\"\nTo which Jane replies, \"If I'd known you had more time, I would have taken off my pantyhose!\"",
  "Little Johnny came into the bathroom while his mother was taking a shower. He asked, \"Mum,\nwhat's that between your legs?\"\nShe told him that was her squirrel.\nLater that day he was in the bathroom again while Gran was taking a shower and he asked, \"Gran, what's that between your legs?\"\nShe replied, \"That's my squirrel.\"\nThen little Johnny said, \"Mommy has one too, but hers is not as grey as yours.\"\nGrandma replied, \"That's because your mum's squirrel hasn't cracked as many nuts as mine has!\"",
  "Little Johnny, then a teenager, and his grandfather go fishing one day. While fishing, the old man starts talking about how times have changed.\nThe young man picks up on this and starts talking about the various problems and diseases going around.\nLittle Johnny says, \"Grandpa, they didn't have a whole lot of problems with all these diseases when you were young did they?\"\nGrandpa replies, \"Nope.\"\nLittle Johnny says, \"Well, what did you guys use for safe sex?\"\nGrandpa replies, \"A wedding ring.\"",
  "A husband comes home to find his wife with her suitcases packed in the living room. \"Where the hell do you think you're going?\" he says. \"I'm going to Las Vegas. You can earn \$400 for a blow job there, and I figured that I might as well earn money for what I do to you free.\"\nThe husband thinks for a moment, goes upstairs, and comes back down, with his suitcase packed as well. \"Where do you think you going?\" the wife asks. \"I'm coming with you...I want to see how you survive on \$800 a year!!!\"",
  "As a painless way to save money, a young couple arranged that every time they have sex the husband puts his pocket change into a china piggy bank on the bedside table. One night while being unusually athletic, he accidentally knocked the piggy bank onto the floor where it smashes.\nTo his surprise, among the masses of coins, there are handfuls of five and ten dollar bills. He asks his wife \"What's up with all the notes?\", to his wife which replies, \"Well, not everyone is as cheap as you are.\"",
  "A husband comes home to find his wife with her suitcases packed in the living room. \"Where the hell do you think you're going?\" he says. \"I'm going to Las Vegas. You can earn \$400 for a blow job there, and I figured that I might as well earn money for what I do to you free.\"\nThe husband thinks for a moment, goes upstairs, and comes back down, with his suitcase packed as well. \"Where do you think you going?\" the wife asks. \"I'm coming with you...I want to see how you survive on \$800 a year!!!\"",
  "An insect falls into a mug of beer.\nEnglish Man: Throws his mug of bear on the floor and walks out.\nAmerican Man: Takes out the insect and drinks tbe beer.\nChinese Man: Eats the insect and throws the beer.\nIndian Man: Sells the insect to the Chinese and the beer to the Englishman and buys himself a new mug of beer.\nPakistani Man: Accuses the Indian of throwing the insect into his mug, relates the issue to Kashmir, asks the Chinese for military aid and takes a loan to buy another mug of beer.",
  "One day, little Johnny was walking into his classroom with his hand down his pants. \"What is you're hand doing down there?!\" Said his teacher. \"It hurts.\" Said Johnny. \"Then go to the nurses office to see if you can go home.\" Said Johnny's teacher. About 10 minutes later Johnny comes back inside the classroom with his dick sticking out. \"JOHNNY! WHY IS THAT OUT?!\" Says his teacher. \"My mom told me that if I could stick it out until noon she would come pick me up.\"",
  "There was a boy playing in the farm field when his mom called him in for breakfast. On his way in he kicked a cow, pig, and a chicken. So when he gets to the table he sees a dry bowl of cereal. \"What's the deal?\" he asks. His mom says \" You kicked the cow so no milk for you, you kicked the pig so no bacon for you, and you kicked the chicken so no eggs for you.\" Then his father walks into the kitchen and accidentally kicked the cat. The the boy says \"Do you want me to tell him or should you?\"",
  "There was a boy playing in the farm field when his mom called him in for breakfast. On his way in he kicked a cow, pig, and a chicken. So when he gets to the table he sees a dry bowl of cereal. \"What's the deal?\" he asks. His mom says \" You kicked the cow so no milk for you, you kicked the pig so no bacon for you, and you kicked the chicken so no eggs for you.\" Then his father walks into the kitchen and accidentally kicked the cat. The the boy says \"Do you want me to tell him or should you?\"",
  "At the cinema a man noticed a young woman sitting all by herself. He was excited to see she had both hands under her skirt and was fingering herself furiously. He moved to the next seat to her and offered his help. She welcomed his help, and so the man started fingering her like crazy. When he tired and withdrew his hand, he was surprised to see\nher go back to work on herself with both hands. Wasn't I good enough?\" he asked sheepishly. \"Great,\" she said, \"but these crabs are still itching!\"",
  "As a painless way to save money, a young couple arranged that every time they have sex the husband puts his pocket change into a china piggy bank on the bedside table. One night while being unusually athletic, he accidentally knocked the piggy bank onto the floor where it smashes.\nTo his surprise, among the masses of coins, there are handfuls of five and ten dollar bills. He asks his wife \"What's up with all the notes?\", to his wife which replies, \"Well, not everyone is as cheap as you are.\"",
  "A man is at the dentist?s for a checkup. As the dentist leans over, he asks, ?Well? So you had oral sex this morning?? ?How did you know?? asks the man, embarrassed but also amazed at his dentist?s perception. ?Was it the smell on my breath?? ?No? says the dentist. ?Well, did you see a pubic hair caught in my teeth?? asks the man. ?No? says the dentist. ?Well, what then? How did you know?? asks the man, losing patience. The dentist says ?There?s a little bit of shit on the end of your nose.?",
  "Little Johnny was headed to Tommy?s house it was raining out so he had his yellow raincoat and hat, he was pulling his wagon and it got stuck in the mud so little Johnny threw his hat to the ground and started swearing and then he heard a voice little Johnny don't swear god is every where so he said really is god in my friend Tommy?s house god said yes Johnny god is every so he said is god in my wagon god said yes little Johnny god is every where then Johnny said well then get out and push!",
  "In the days before birth control pills, a young bride-to-be asked her gynecologist to recommend some sort of contraceptive. He suggested she try withdraw, douches or condoms. Several years later, the woman was walking down the street with three children when she happened to run across her old doctor. \"I see you decided not to take my advice,\" he said, eyeing the young children. \"On the contrary, doc,\" she exclaimed, \"Davey here was a pullout, Darcy was a washout, and Delores was a blowout!\"",
  "A husband comes home to find his wife with her suitcases packed in the living room. ?Where the hell do you think you?re going?? he says. ?I?m going to Las Vegas. You can earn \$400 for a blow job there, and I figured that I might as well earn money for what I do to you free.?\nThe husband thinks for a moment, goes upstairs, and comes back down, with his suitcase packed as well. ?Where do you think you going?? the wife asks. ?I?m coming with you?I want to see how you survive on \$800 a year!!!?",
  "Little Johnny walked in on his parents having sex one night.ÿ His dad looked at him and asked do you want us to make you a little brother?ÿ Little Johnny said nope.ÿ The next night he walked in on them again.ÿ His dad asked if he wanted them to make him a little sister.ÿÿ He said nope.ÿ The next night he caught them at it again.ÿ His dad just looked at Johnny.ÿ Johnny looked at his dad a minute and said, why don't y'all do it doggie style and make me a puppy.",
  "A teacher was wrapping up class, and started talking about the next day?s final exam. He said there would be no acceptable excuses for failing to show up to the exam, barring a dire medical condition or an immediate family member?s death. One male student raised his hand and asked, ?What about extreme sexual exhaustion?? The students in the classroom burst into laughter, and after subsiding the teacher glared at the student and said ?That?s no excuse, you can use your other hand to write.?",
  "There were three ducks swiming in a pond one night after midnight and got arrested for trespassing. They were called to apper in court the next day so the judge called up duck #1 and asked what were you doing in a pond swiming after midnight the duck said \"blowing bubbles\" So then the judge called up duck #2 and asked the same question and the duck said \"blowing bubbles\". Then the judge called up duck #3 and said let me guess you were blowing bubbles to and the duck said \"No i am BUBBLES\"",
  "There were three ducks swiming in a pond one night after midnight and got arrested for trespassing. They were called to apper in court the next day so the judge called up duck #1 and asked what were you doing in a pond swiming after midnight the duck said \"blowing bubbles\" So then the judge called up duck #2 and asked the same question and the duck said \"blowing bubbles\". Then the judge called up duck #3 and said let me guess you were blowing bubbles to and the duck said \"No i am BUBBLES\"",
  "Little johnny asks his mom how to tell a girl he liks her. She says \"Just express your fellings.\" The next day he goes to school and takes the girl into a room and locks the door. He then ripps her clothes off and stars fucking her. Shocked she says \"what are you doing.\" The he replies \"I'm expressing my feelings for you, the same way my daddy does with mommy, but I think its missing somthing, oh yah, you aren't screaming \"oooh, fuck me harder, god I'm cuming.\"",
  "The artist tried to concentrate on his work, but the attraction he felt for his model finally became irresistible. He threw down his palette, took her in his arms, and kissed her. She pushed him away. \"Maybe your other models let you kiss them,\" she said, \"but I'm not that kind!\" \"Actually, I've never tried to kiss a model before,\" he protested. \"Really?\" she said, softening. \"Well, how many models have there been?\" \"Four so far,\" he replied, thinking back. \"A jug, two apples and a vase.\"",
  "Two pieces of string meet one day in the park and while one goes on the slide the other goes on the swings. They're having a great time until one string decides to go on the roundabout.\nAfter a while, the string feels really dizzy and falls off, scraping across the tarmac and making as tangled mess of one end and falling in a heap. The second string looked at him and sighed \"you're not very good on that roundabout are you?\"\nThe first string looked at himself and said \"I'm a frayed knot\".",
  "Two old friends are having coffee when the first woman says, \"I hear that you've been telling people that I'm ugly!\"\n\"Oh no, I've just been saying that your new hairdo makes you look less attractive.\"\n\"I also heard that you've been calling me fat!\"\n\"Oh no, I just said that the way you wear those stripes makes you look larger than you really are.\"\n\"I've also heard that you're saying that my husband has a wart on his dick!\"\n\"Oh no, I only said that it feels like he has a wart on his dick!\"",
  "A boy was walking down the street when he noticed his grandpa sitting on the porch, in the rocking chair, with nothing on from the waist down. \"Grandpa what are you doing?\" he exclaimed. The old man looked off in the distance and did not answer him. \"Grandpa, what are you doing sitting out here with nothing on below the waist?\" he asked again. The old man slowly looked at him and said, \"Well, last week I sat out here with no shirt on, and I got a stiff neck. This is your Grandma's idea.\"",
  "A boy was walking down the street when he noticed his grandpa sitting on the porch, in the rocking chair, with nothing on from the waist down. \"Grandpa what are you doing?\" he exclaimed. The old man looked off in the distance and did not answer him. \"Grandpa, what are you doing sitting out here with nothing on below the waist?\" he asked again. The old man slowly looked at him and said, \"Well, last week I sat out here with no shirt on, and I got a stiff neck. This is your Grandma's idea.\"",
  "A doctor had just finished a marathon sex session with one of his patients. He was resting afterwards and was feeling a bit guilty because he thought it wasn't really ethical to screw one of his patients.\n\nHowever, a little voice in his head said Lots of other doctors have sex with their patients, ... so it's not like you're the first ...\n\nThis made the doctor feel a little bit better until still another voice in his head said, but then again ... they probably weren't veterinarians ...",
  "Little Johnny goes to his sister's room and picks up something. His sister tells him to give it back, she wants to keep it as a souvenir. He asks her what it is. She says, \"it's a donut.\" Then Little Johnny says, \"give me fifty cents.\" Johnny gives her the used condom, and his sister gives him 50 cents. He goes to the kitchen with a big smile on his face, and his mom asks him why he's smiling. He says, \"My sister gave me fifty cents for a donut, but I already licked out all the custard!",
  "Little Johnny goes to his sister's room and picks up something. His sister tells him to give it back, she wants to keep it as a souvenir. He asks her what it is. She says, \"it's a donut.\" Then Little Johnny says, \"give me fifty cents.\" Johnny gives her the used condom, and his sister gives him 50 cents. He goes to the kitchen with a big smile on his face, and his mom asks him why he's smiling. He says, \"My sister gave me fifty cents for a donut, but I already licked out all the custard!",
  "A man was just waking up from anaesthesia after surgery and his wife was sitting by his side. His eyes fluttered open and he said, ?You?re so beautiful.? Then he fell asleep again. His wife had never heard him say that, so she stayed by his side. A few minutes later, his eyes fluttered open and he said, ?You?re so cute!? The wife was disappointed because instead of ?beautiful? it was now ?cute?. She asked him, ?What happened to ?beautiful??? The man replied, ?The drugs are wearing off!?",
  "After church, Johnny tells his parents he has to go and talk to the minister right away.They agree and the pastor greets the family.\n\"Pastor,\" Johnny says, \"I heard you say today that our bodies came from the dust.\"\n\"That's right, Johnny, I did.\"\n\"And I heard you say that when we die, our bodies go back to dust.\"\n\"Yes, I'm glad you were listening.Why do you ask?\"\n\"Well you better come over to our house right away and look under my bed 'cause there's someone either comin' or goin'!\"",
  "A guy's walking down the boardwalk in Atlantic City and he runs into a hooker. He says, \"How much?\" She says \"Twenty bucks.\" He says, \"All right.\" They climb down under the boardwalk, and he bangs her. The next night, he runs into the same hooker, they go under the boardwalk, only this time while he's banging her, she blasts two incredible farts. When they get done, he hands her twenty-five dollars. She says, \"What's the extra five?\" He says, \"That's for blowing the sand off my balls.\"",
  "A little girl walks into her parents' bathroom and notices for the first time, her father's nakedness.\nImmediately, she is curious: he has equipment that she doesn't have. She asks, \"What are those round things hanging there, daddy?\"\nProudly, he replies, \"Those, sweetheart, are God's Apples of Life.\nWithout them we wouldn't be here.\"\nPuzzled, she seeks her mommy out and tells her what daddy has said.\nTo which mommy asks, \"Did he say anything about the dead branch they're hanging from?",
  "\"Daddy, where did I come from?\" seven-year-old Rachel asks. It is a moment for which her parents have carefully prepared. They take her into the living room, get out several other books, and explain all they think she should know about sexual attraction, affection, love, and reproduction. Then they both sit back and smile contentedly. \"Does that answer your question?\" the mom asks. \"Not really,\" the little girl says. \"Judy said she came from Detroit. I want to know where I came from.\"",
  "Tom had this problem of getting up late in the morning and was always late for work. His boss was mad at him and threatened to fire him if he didn't do something about it. So Tom went to his doctor who gave him a pill and told him to take it before he went to bed.Tom slept well and in fact beat the alarm in the morning. He had a leisurely breakfast and drove cheerfully to work. \"Boss,\" he said, \"The pill actually worked!\"\"That's all fine\" said the boss. \"But where were you yesterday?\"",
  "A blind man was traveling in his private jet when he detected something was wrong. He made his way to the cockpit and got no response from his pilot. The blind guy then found the radio and started calling the tower. ?Help! Help!? The tower came back and asked, ?What?s the problem?? The blind guy yelled, ?Help me! I?m blind? the pilot is dead, and we?re flying upside down!? The tower comes back and asked, ?How do you know you?re upside down?? ?Because the shit is running down my back!?",
  "\"Father, how am I going to tell my husband that I am still a virgin?\"\n\"My child, you have been a married woman for many years. You have had three husbands! Surely that cannot be.\"\n\"Well, father, my first husband was a psychologist, and all he wanted to do was talk, and the next one was in construction and he always said he'd get to it tomorrow. The last one was a gynecologist and all he did was look. But this time, father, I'm marrying a lawyer and I'm sure I'm going to get screwed.\"",
  "Once Johnny walked in on his dad and he was drinking a beer Johnny said can I have some and the dad said can your dick touch your ass and the kid said no and then he couldn't, later his dad was smoking and he said can I have some and the dad said can your dick touch your ass and then he couldn't later his mom baked some cookies and his dad said can I have one and Johnny said can your dick touch your ass and the dad said yeah and Johnny said then go fuck yourself these are my cookies.",
  "So this older guy goes to the doctor asking for a prescription for 'Viagra'. The guy asks for a large dose of the *strongest* variety. The doctor asks why he needs so much. The guy says that two young nymphomaniacs are spending a week at his place. The doctor fills the prescription.\nLater that week, the same guy goes back to the doctor asking for pain killers. The doctor asks 'why, is your dick in that much pain?', 'no', says the guy, 'it's for my wrists - the girls never showed up!'",
  "So this older guy goes to the doctor asking for a prescription for 'Viagra'. The guy asks for a large dose of the *strongest* variety. The doctor asks why he needs so much. The guy says that two young nymphomaniacs are spending a week at his place. The doctor fills the prescription.\nLater that week, the same guy goes back to the doctor asking for pain killers. The doctor asks 'why, is your dick in that much pain?', 'no', says the guy, 'it's for my wrists - the girls never showed up!'",
  "Darren marries this girl, and they go on their honeymoon. He leaves the room the first night to go down to the lobby to get a pack of cigarettes. When he gets back, his bride is lying on the bed naked fucking one of the bellhops. Another one is under her, getting her in the ass. She's sucking off the desk clerk, and she's jerking off a cab driver and the dishwasher. Darren screams, \"What the fuck are all these jerk-offs doing in here?\" She says, \"Well, you always knew I was a flirt.\"",
  "A man walks up to a woman in his office each day, stands very close to her, draws in a large breath of air and tells her that her hair smells nice.\nAfter a week of this she can't stand it any longer! The woman goes into her supervisor's office and tells him that she wants to file a sexual harassment suit against the man and explains why.\nThe supervisor is puzzled by this and says, \"What's wrong with the co-worker telling you your hair smells nice?\"\nThe woman replies, \"He's a midget!\"",
  "A Mormon was seated next to an Irishman on a flight from London. After the plane was airborne, drink orders were taken. The Irishman asked for a whiskey, which was promptly brought and placed before him.\n\nThe flight attendant then asked the Mormon if he would like a drink. He replied in disgust, \"I'd rather be savagely raped by a dozen whores than let liquor touch my lips.\"\n\nThe Irishman then handed his drink back to the attendant and said, \"Me,\ntoo, I didn't know we had a choice.\"",
  "One day little Johnny was walking home when a lady in a black car pulls up next to him. \"do you want some candy?\" asked the lady. Johnny was always curious what would happen if he said yes, so he did. He got in the car and the lady drove him to her house. When they are inside she says \"the candy is in my pants but you got to get it with your penis\" and Johnny says \"lady, if u wanted to have sex you could have just asked instead of bribing me with candy\"",
  "Little Johnny and his dad went upstairs one day to hang a picture and frame while mom made lunch.About twenty minutes after they went upstairs Little Johnny came downstairs crying.\n\"What's wrong?\" His mother said.\n\"Daddy slipped and hit his thumb with the hammer!\" said Little Johnny.\n\"Well...\" Little Johnny's mother said, \"That's nothing to cry about, daddy will be okay.It's actually kind of funny, I don't know why you didn't laugh when it happened.\"\n\"I did!\" Little Johnny said.",
  "One day Little Johnny was walking by his sisters room. She was doing something strange and had the door locked. So he asked his mommy, \"Mom?\" \"Yes Johnny?\" She replied...\"Why is sissy making funny noises while her phone is vibrating?\" he says...his mommy didn't know what to say so she said \"Why don't you go ask her yourself\". Little Johnny walked back up stairs to find his old sister heading to the bath room to return Little Johnny's electric toothbrush.",
  "A woman came home just in time to find her husband in bed with another woman. With superhuman strength borne of fury, she dragged her husband down the stairs to the garage and put his penis in a vise. She then secured it tightly and removed the handle. Next she picked up a hacksaw. The husband terrified, screamed, \"Stop! Stop! You're not going to......to....cut it off are you?!\" The wife, with a gleam of revenge in her eye, said, \"Nope. You are. I'm going to set the garage on fire.\"",
  "Little Johnny always hear his teacher say \"that?s not the question I?m looking for but I like the way your thinking.\" So instead of answering her question Johnny asked \"Teacher if you walk in a ice cream store and you see 3 ladies there sucking, blowing, and going all around how do you know which on is married\" the teacher said nervously \"Ummm Johnny the one....blowing\" Johnny said \"Nooo the one that?s wearing a wedding ring that?s the wrong answer but I like the way your thinking\"",
  "This little girl walks over to her grandmother and asks \"Granny, can you show me a magic trick?\" \"No dear, but I think your grand father knows one.\" So the little girl walks over to her grandpa and asks \"Grandpa, granny says you know some magic tricks, could you show me one?\" The grand father looks at her, \"Sure, just hop on my lap!\" So the little girl jumps on his lap. \"Now, can you feel a finger poking up your ass?\" asks the grandpa, \"Yeah\" replies the girl \"Well look, no hands!\"",
  "A young guy was laying on his back on a massage table, wearing only a towel over his groin. A young and stunningly attractive Swedish girl was massaging his shoulders, then his chest, and gradually worked her way down his torso. The guy was getting sexually excited as the masseur approached the towel. The towel began to lift and the Swedish girl arched her eyebrows. ?You wanna wank?? she asked. ?You bet!? came the excited reply. ?Alright?? she said. ?I?ll come back in ten minutes.?",
  "A man comes home late one night, drunk.\n\"Where have you been?\"\nasks his wife.\n\"In the Golden Bar! They have golden chairs, golden glasses, golden beer, and a golden urinal!\" This sounds awfully suspicious to the wife, who calls the Golden Bar.\n\"Do you have golden chairs?\"\n\"Yes.\"\n\"Do you have golden glasses?\"\n\"Yes.\"\n\"Do you have golden beer?\"\n\"Yes.\"\n\"Do you have a golden urinal?\"\n\"Hold on.\"\nOn the other end, she hears \"I think we have a line on the guy who pissed in your saxophone.\"",
  "Little Johnny mom goes in for a conference and asks a teacher to watch him he ask teacher take off you top she says no Johnny he says PLEASEEEE she says OK Johnny then he says teacher take off you pants she says no Johnny he says please she says alright Johnny then he ask take off the rest of your stuff she says no Johnny he says please she says ok he asks teacher lay on this desk she says no he says please al right his mom comes in and says deeper he says I cant I'm already stuck",
  "A guy phones up his Boss, but gets the bosses' wife instead. \"I'm afraid he died last week.\" she explains. The next day the man calls again and asks for the boss. \"I told you\" the wife replies, \"he died last week.\" The next day he calls again and once more asks to speak to his boss. By this time the wife is getting upset and shouts, \"I'VE ALREADY TOLD YOU TWICE, MY HUSBAND, YOUR BOSS, DIED LAST WEEK! WHY DO YOU KEEP CALLING?\" \"Coz,\" he replied laughing, \"I just love hearing it...\"",
  "3 guys walk into a bar. The first guy says \"I have got the smallest arm in? the world\" \nThe second guy \"I have the smallest head in the world\" \nThe third guy \"I have got the smallest d*ck in the world\" \nThe 3 guys go to the Guinness World Records \nThe first guy comes back and says \"I really do have? the smallest? arm in the world\" \nThe second guy comes back and says \"Amazing, I do have the smallest head in the world\" \nThe third guy comes back angry \" Who the F*CK is JUSTIN BEIBER?",
  "Little Johnny is sitting in class, and the teacher says, \"Today, children, we are going to learn multi-syllable words. Does anybody have an example of a multi-syllable word?\"\nLittle Johnny waves his hand, \"Me, Miss Rogers, me, me!\"\nMiss Rogers says, \"Alright, little Johnny, what is your multi-syllable word?\"\nLittle Johnny says, \"Masturbate.\"\nMiss Rogers smiles and says, \"Wow, little Johnny, that's a mouthful.\"\nLittle Johnny says, \"No, Miss Rogers, you're thinking of a fel-a-tio.\"",
  "Bruce is driving over the Sydney Harbor Bridge one day when he sees his girlfriend, Sheila about to throw herself off. Bruce slams on the brakes and yells, \"Sheila, what the hell d'ya think you're doing?\" Sheila turns around with a tear in her eye and says, \"G'day Bruce. Ya got me pregnant and so now I'm gonna kill myself.\" Bruce gets a lump in his throat when he hears this. He says \"Strewth Sheila... Not only are you a great shag, but you're a real sport too.\" ...and drives off.",
  "One day in school, the teacher decides to play 20 questions.\nSo the teacher says \"OK kids, I am thinking of something round, and red\"\nLittle Suzy pipes up \"I know, it's a tomato\".\n\"No but you're thinking, it's an apple\" replies the teacher.\nSo Little Johnny stands up, places his hand in his pocket and says \"I am holding onto something that is round, hard, and has a head on it\"\n\"Go to the principals office\" says the teacher.\n\"No but you're thinking\", say Johnny, \"It's a quarter\"",
  "Little Johnny was out with his grandmother when they came across a couple of dogs mating on the sidewalk.\n\"What are they doing, grandma?\" asked little Johnny.\nThe grandmother was embarrassed, so she replied, \"The dog on top has hurt his paw, and the one underneath is carrying him to the doctor.\"\n\"They're just like people, aren't they grandma?\" said little Johnny.\n\"How do you mean?\" asked grandma.\n\"Offer someone a helping hand,\" said little Johnny, \"and they fuck you everytime!\"",
  "One day little johnnywas sittingin class when the teacher ask the class what they did on the weekend. little johnny raised his hand. The teacher called on him he said I played with my stuttering cat. The teach said there was no such thing. Johnny replying with yes there is. I was playing with him the other day when a huge dog jumps over the fence. my cat raisedhis back and went ffffffffff fffffff fffffff and before he could say fuck. The dog grabbedhim.",
  "A class professor was giving a lecture on company slogans and was asking his students if they were familiar with them.\n\"Joe,\" he asked, \"which company has the slogan, 'Come fly the friendly skies'?\"\nJoe answered the correct airline.\n\"Brenda, can you tell me which company has the slogan, 'Don't leave home without it'?\"\nBrenda answered the correct credit card company with no difficulty.\n\"Now Johny, tell me which company bears the slogan, 'Just do it'?\"\nAnd Johny answered, \"Mom.\"",
  "A mother took her little boy to church.\nWhile in church the little boy said, \"Mommy, I have to pee.\"\nThe mother said to the little boy, \"It's not appropriate to say the word 'pee' in church. So, from now on whenever you have to 'pee' just tell me that you have to 'whisper'.\"\nThe following Sunday, the little boy went to church with his Father and during the service said to his father, \"Daddy, I have to whisper.\"\nThe Father looked at him and said, \"Okay, just whisper in my ear.\"",
  "Noticing that her boss's fly was open, an embarrassed secretary told him as she left the office, \"Your garage door is open.\"\nThe bewildered executive didn't know what she meant until a co-worker finally told him what she was referring to.\nThe next day, he called his secretary into his office and said, \"Yesterday, when my garage door was open, did you see a long red Cadillac with a hard top?\"\n\"Oh, no,\" she replied. \"It was a little pink Volkswagen with two flat tires up front.\"",
  "A midget walks into a bathroom and sees a guy taking a piss, he comes up to him and says, \"You have nice balls\", the guy liking compiments says, \"Um..... thanks I guess\", then the midget says, \"Can I have a closer look at them, you know mine are so small!\"\nThe guy answers, \"um..... sure go ahead\", so the midget gets a 4 foot ladder, climbs up onto it and grabs the guys balls, then all of a sudden he yanks on them keeping a tight grip he says, \"Give me your wallet or i'll jump!\"",
  "A man was just waking up from anesthesia after surgery, and his wife was sitting by his side. His eyes fluttered open and he said, \"You're beautiful.\" Then he fell asleep again. His wife had never heard him say that, so she stayed by his side. A few minutes later, his eyes fluttered open and he said, \"You're cute!\" The wife was disappointed because instead of \"beautiful,\" it was now \"cute.\" She said, \"What happened to 'beautiful'?\" The man replied, \"The drugs are wearing off!\"",
  "In biology class, a young teacher draws a cucumber on the blackboard.\n''Children, could anyone tell me what this?''\nLittle Johnny raises hand, ''It's a dick, Miss!''\nThe young teacher, extremely embarrassed, blushes and awkwardly leaves the classroom. A minute later, the headteacher walks in,\n''All right, what have you done now, Johnny? It's something new every day! Yesterday you break window, and today...,'' he looks around, ''...and today you draw dick on the blackboard!''",
  "A young woman was having a physical examination and was very embarrassed because of a weight problem. As she removed her last bit of clothing, she blushed. \"I'm so ashamed, Doctor,\" she said, \"I guess I let myself go.\" The physician was checking hers eyes and ears. \"Don't feel ashamed, Miss. You don't look that bad.\"\n\"Do you really think so, Doctor?\" she asked. The doctor held a tongue depressor in front of her face and said, \"Of course. Now just open your mouth and say moo.\"",
  "A young woman was having a physical examination and was very embarrassed because of a weight problem. As she removed her last bit of clothing, she blushed. ?I?m so ashamed, Doctor,? she said, ?I guess I let myself go.? The physician was checking hers eyes and ears. ?Don?t feel ashamed, Miss. You don?t look that bad.?\n?Do you really think so, Doctor?? she asked. The doctor held a tongue depressor in front of her face and said, ?Of course. Now just open your mouth and say moo.?",
  "A simple young man got very drunk one day and was caught short on the way home so he relieved himself in the local river. At that moment a policeman came along and shouted to him. \n?Stop that immediately, put it away and go home, you drunken sod.? \n\nThe man stuck his dick back inside his trousers and started to laugh. \n\n?What the hell are you laughing at?? demanded the policeman. \n\n?Ha, ha,? replied the man. ?I really tricked you this time. I put it away but I didn?t stop.?",
  "A first grade teacher had a small number of children gathered around a table for a reading group.After the story was read she gave the children a work sheet to do. She thought they may have some problems so wanted them to work on it there.\nShe heard little Johnny say very softly \"damn !\"\nThe teacher leaned over and said quietly, \"We don't say that in school.\"\nLittle Johnny looked at the teacher, his eyes got very big and he said, \"Not even when things are all fucked up ?!\"",
  "This guy visits the doctors and says, \"Doc, I think I've got a sex problem. I can't get it up for my wife anymore.\" The doctor says, \"Come back tomorrow and bring her with you.\" The next day, the guy shows up with his wife. The doctor says to the wife, \"Take off your clothes and lie on the table.\" She does it, and the doctor walks around the table a few times looking her up and down. He pulls the guy to the side and says, \"You're fine. She doesn't give me a hard-on, either.\"",
  "Little Johnny was sitting in class one day. All of the sudden, he needed to go to the bathroom. He yelled out,\"Miss Jones, I need to take a piss!!\"\n\nThe teacher replied, \"Now, Johnny, that is NOT the proper word to use in this situation. The correct word you want to use is 'urinate.'\n\nPlease use the word 'urinate' in a sentence correctly, and I will allow you to go.\"\n\nLittle Johnny thinks for a bit, then says, \"You're an eight, but if you had bigger tits, you'd be a ten!!!\"",
  "Little Johnny was sitting in the park one day eating chocolate bars.\n\nAn old man comes along and sits next to him.\n\nLittle Johnny proceeds to eat more bars.\n\nAfter the forth bar the man says to him don't you think your eating too many chocolate bars.\n\nLittle Johnny tells says to him my grandfather lived to be 110 years old.\n\nThe old man looking surprised said really from eating a lot of chocolate bars like that.\n\nLittle Johnny says no from minding his own fracking business.",
  "A teacher was giving a talk on company slogans and was asking his students if they were familiar with them.\n\"Joe,\" he asked, \"which company has the slogan, 'Come fly the friendly skies'?\"\nJoe answered the correct airline.\n\"Brenda, can you tell me which company has the slogan, 'Don't leave home without it'?\"\nBrenda answered the correct credit card company with no difficulty.\n\"Now Jonny, tell me which company bears the slogan, 'Just do it'?\"\nAnd Little Jonny answered, \"Mom.\"",
  "This guy visits the doctors and says, ?Doc? I think I?ve got a sex problem. I can?t get it up for my wife anymore.? The doctor says, ?Come back tomorrow and bring her with you.? The next day, the guy shows up with his wife. The doctor says to the wife, ?Take off your clothes and lie on the table.? She does it, and the doctor walks around the table a few times looking her up and down. He pulls the guy to the side and says, ?You?re fine. She doesn?t give me a hard on either.?",
  "The day after meeting three women in a bar, the guys tried to guess the professions of their dates. The first must have been with a nurse because she had said, \"lie back, this won't hurt a bit.\" The second must have been a teacher because she had said, \"you're going to do this over and over until you get it right.\" The last speculated that his date must have been a flight attendant because she had said, \"place this over your mouth and nose and continue to breathe normally.\"",
  "Q: You are driving in a car at a constant speed. On your left side is a drop-off, and on your right side is a fire engine traveling at the same speed as you. In front of you is a galloping horse, which is the same size as your car and you cannot overtake it. Behind you is a galloping zebra. Both the horse and zebra are also traveling at the same speed as you. What must you do to safely get out of this highly dangerous situation?\nA: Get your drunk-ass off the merry-go-round.",
  "There are three Jewish mothers bragging about their sons. The first one says \"My son is very successful. He is the best lawyer in New York City.\"The second one says, \"My son has done better than that. He is the best doctor in New York City.\"The third one says, \"My son has not done that well. He does not have a very good job, and he is homosexual. But he has these two great boyfriends... One is the best lawyer in New York City, and the other is the best doctor in the city.\"",
  "One day Little Johnny came home from school and asked his mom what they were having for dinner. She said that it was a surprise and him and his brother would have to guess what it is after they try it. Well dinner time came and they started eating it, but they couldn't figure out what it was. So Little Johnny asked his mom for a hint. She said, \"Okay, I'll give you a hint. I call your father this.? Little Johnny said to his brother,? Quick Bobby, spit it out, its asshole!\"",
  "Little Johnny goes to school, and the teacher says \"Today we are going to learn multi-syllable words, class. Does anybody have an example of a multi-syllable word?\"\nLittle Johnny waves his hand, \"Me, miss, me, me!\"\nTeacher says \"All right, Little Johnny, what is your multi-syllable word?\"\nLittle Johnny says \"Mas-tur-bate.\"\nTeacher smiles and says \"Wow, little Johnny, that's a mouthful.\"\nLittle Johnny says \"No, miss, you're thinking of a blowjob. I'm talking about a wank.\"",
];

int currentJokeIndex = 0;
List<String> newDataList = List.from(jokesItems);
void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var _textController;

  @override
  Widget build(BuildContext context) {
    final title = 'Adult Jokes';
    return MaterialApp(
      title: title,
      home: Scaffold(
          appBar: AppBar(
            title: Text(title),
            backgroundColor: Colors.red[900],
          ),
          body: Column(
            children: [
              new Card(
                child: new ListTile(
                  leading: new Icon(Icons.search),
                  title: new TextField(
                    controller: _textController,
                    decoration: new InputDecoration(
                        hintText: 'Search Jokes...', border: InputBorder.none),
                    onChanged: onItemChanged,
                  ),
                  trailing: IconButton(
                      icon: Icon(
                        Icons.cancel,
                      ),
                      onPressed: () {
                        _textController.clear();
                      }),
                ),
              ),
              Expanded(
                child: ListView.builder(
                  itemCount: newDataList.length,
                  itemBuilder: (context, index) {
                    return ListTile(
                        leading: Icon(Icons.tag_faces),
                        title:
                            Text('${newDataList[index].substring(0, 34)}...'),
                        tileColor: (index % 2 == 0)
                            ? Colors.amber[200]
                            : Colors.amber[100],
                        onTap: () {
                          currentJokeIndex = index;
                          print(currentJokeIndex);
                          Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) => JokesScreen()));
                        });
                  },
                ),
              )
            ],
          )),
    );
  }

  void onItemChanged(String value) {
    setState(() {
      newDataList = jokesItems
          .where((string) => string.toLowerCase().contains(value.toLowerCase()))
          .toList();
    });
  }
}

class JokesScreen extends StatefulWidget {
  @override
  _JokesScreenState createState() => _JokesScreenState();
}

class _JokesScreenState extends State<JokesScreen> {
  int _selectedIndex = 0;

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
      switch (index) {
        case 0:
          if (currentJokeIndex > 0) {
            currentJokeIndex -= 1;
          }
          print(currentJokeIndex);
          break;
        case 2:
          if (currentJokeIndex < jokesItems.length) {
            currentJokeIndex += 1;
          }
          print(currentJokeIndex);
          break;
        default:
          currentJokeIndex = Random().nextInt(jokesItems.length);
          print(currentJokeIndex);
        // widget.content = jokesItems[10];
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Adult Jokes'),
        backgroundColor: Colors.red[900],
      ),
      body: SingleChildScrollView(
        // scrollDirection: Directi,
        child: Column(
          children: [
            Container(
              padding: EdgeInsets.all(30),
              child: Text(
                newDataList[currentJokeIndex],
                style: new TextStyle(
                  fontSize: 22.0,
                  color: Colors.red[600],
                ),
              ),
            ),
            Align(
              alignment: Alignment.bottomRight,
              child: Image.asset('assets/meme.png', width: 150, height: 150),
            )
          ],
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        backgroundColor: Colors.red[800],
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.navigate_before),
            label: 'Before',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.shuffle),
            label: 'Random',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.navigate_next),
            label: 'Next',
          ),
        ],
        unselectedItemColor: Colors.white,
        currentIndex: _selectedIndex,
        selectedItemColor: Colors.amber[800],
        onTap: _onItemTapped,
      ),
    );
  }
}
